name: wakoody
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1 # for translation
  flutter_phoenix: ^1.1.0   #for reset the app after change the language
  shared_preferences: ^2.0.15 # local storage
  flutter_riverpod: ^2.1.1   #state management
  http: ^0.13.5      # calling APIs
  geocoding: ^2.0.5  #  get address from coordinates
  geolocator: ^9.0.2  # get the location
  fluttertoast: ^8.1.1 # show toast message on the screen
  file_picker: ^5.2.3
#  path_provider: ^2.0.11
#  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6 # for save and get images to file
  get_it: ^7.2.0  # for dependency injection
  mac_address: ^1.0.0 # get macAddress of the device
  #get_mac_address: ^0.0.2 # get macAddress of the device
  pinput: ^2.2.16 # for OTP verification

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
